-- ==========================================
-- FIRE / EMS – Core Schema (PostgreSQL DDL)
-- Author: Andrew Tellez, 1/14/2026
-- ==========================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS fire_ems;
SET search_path = fire_ems, public;

-- ---------- incident ----------
CREATE TABLE incident (
  incident_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  basic_incident_number varchar UNIQUE,
  basic_incident_city_name varchar,
  basic_primary_station_name varchar,
  basic_incident_type_code varchar,
  basic_incident_type_code_and_description varchar,
  basic_secondary_station_names_list varchar,
  basic_incident_psap_date_time timestamptz,
  basic_shift_or_platoon varchar,
  basic_incident_year integer,
  basic_incident_month integer,
  basic_incident_day_of_month integer,
  basic_incident_day_of_week integer,
  basic_incident_week integer,
  basic_incident_day_name varchar,
  basic_incident_type varchar,
  basic_incident_postal_code varchar,
  basic_arrival_at_hospital_date_time timestamptz
);

COMMENT ON TABLE incident IS 'CSV Fire “Basic …” fields. One row per incident.';
COMMENT ON COLUMN incident.incident_id IS 'Surrogate key generated by DB';
COMMENT ON COLUMN incident.basic_incident_number IS 'CSV: Basic Incident Number (FD1)';
COMMENT ON COLUMN incident.basic_incident_city_name IS 'CSV: Basic Incident City Name (FD1.16)';
COMMENT ON COLUMN incident.basic_primary_station_name IS 'CSV: Basic Primary Station Name (FD1.4)';
COMMENT ON COLUMN incident.basic_incident_type_code IS 'CSV: Basic Incident Type Code (FD1.21)';
COMMENT ON COLUMN incident.basic_incident_type_code_and_description IS 'CSV: Basic Incident Type Code And Description (FD1.21)';
COMMENT ON COLUMN incident.basic_secondary_station_names_list IS 'CSV: Basic Secondary Station Names List (FD1.4.1)';
COMMENT ON COLUMN incident.basic_incident_psap_date_time IS 'CSV: Basic Incident PSAP Date Time (FD1.51)';
COMMENT ON COLUMN incident.basic_shift_or_platoon IS 'CSV: Basic Shift Or Platoon (FD1.30)';
COMMENT ON COLUMN incident.basic_incident_year IS 'CSV: Basic Incident Year (FD1.3)';
COMMENT ON COLUMN incident.basic_incident_month IS 'CSV: Basic Incident Month (FD1.3)';
COMMENT ON COLUMN incident.basic_incident_day_of_month IS 'CSV: Basic Incident Day Of Month (FD1.3)';
COMMENT ON COLUMN incident.basic_incident_day_of_week IS 'CSV: Basic Incident Day Of Week (FD1.3)';
COMMENT ON COLUMN incident.basic_incident_week IS 'CSV: Basic Incident Week (FD1.3)';
COMMENT ON COLUMN incident.basic_incident_day_name IS 'CSV: Basic Incident Day Name (FD1.3)';
COMMENT ON COLUMN incident.basic_incident_type IS 'CSV: Basic Incident Type (FD1.21)';
COMMENT ON COLUMN incident.basic_incident_postal_code IS 'CSV: Basic Incident Postal Code (FD1.19)';
COMMENT ON COLUMN incident.basic_arrival_at_hospital_date_time IS 'CSV: Basic Arrival At Hospital Date Time (FD1.76)';

-- ---------- incident_sensitive ----------
CREATE TABLE incident_sensitive (
  incident_id integer PRIMARY KEY REFERENCES incident(incident_id) ON DELETE CASCADE,
  basic_authorization_officer_in_charge_name varchar,
  basic_incident_latitude numeric(9,6),
  basic_incident_longitude numeric(9,6),
  basic_incident_full_address varchar
);

COMMENT ON TABLE incident_sensitive IS 'Sensitive/redacted fields for an incident (1:1 with incident).';
COMMENT ON COLUMN incident_sensitive.incident_id IS 'FK to incident (one row per incident)';
COMMENT ON COLUMN incident_sensitive.basic_authorization_officer_in_charge_name IS 'CSV: Basic Authorization Officer In Charge – Name (FD4.2)';
COMMENT ON COLUMN incident_sensitive.basic_incident_latitude IS 'CSV: Basic Incident Latitude (FD1.69)';
COMMENT ON COLUMN incident_sensitive.basic_incident_longitude IS 'CSV: Basic Incident Longitude (FD1.69)';
COMMENT ON COLUMN incident_sensitive.basic_incident_full_address IS 'CSV: Basic Incident Full Address (derived or provided)';

-- ---------- unit_response ----------
CREATE TABLE unit_response (
  response_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id integer NOT NULL REFERENCES incident(incident_id) ON DELETE CASCADE,
  apparatus_resource_id varchar,
  apparatus_resource_type_category varchar,
  apparatus_resource_type_code varchar,
  apparatus_resource_dispatch_date_time timestamptz,
  apparatus_resource_en_route_date_time timestamptz,
  apparatus_resource_arrival_date_time timestamptz,
  apparatus_resource_arrival_at_hospital_date_time timestamptz,
  apparatus_resource_clear_date_time timestamptz,
  apparatus_resource_in_quarters_date_time timestamptz,
  apparatus_resource_in_service_date_time timestamptz,
  apparatus_resource_leave_scene_date_time timestamptz,
  CONSTRAINT uq_unit_response_incident_unit UNIQUE (
    incident_id,
    apparatus_resource_id
  )
);

COMMENT ON TABLE unit_response IS 'One row per apparatus/unit responding to an incident.';
COMMENT ON COLUMN unit_response.incident_id IS 'FK to incident';
COMMENT ON COLUMN unit_response.apparatus_resource_id IS 'CSV: Apparatus Resource ID (FD18.1)';
COMMENT ON COLUMN unit_response.apparatus_resource_type_category IS 'CSV: Apparatus Resource Type Category (FD18.2)';
COMMENT ON COLUMN unit_response.apparatus_resource_type_code IS 'CSV: Apparatus Resource Type Code (FD18.2)';
COMMENT ON COLUMN unit_response.apparatus_resource_dispatch_date_time IS 'CSV: Apparatus Resource Dispatch Date Time (FD18.3)';
COMMENT ON COLUMN unit_response.apparatus_resource_en_route_date_time IS 'CSV: Apparatus Resource En Route Date Time (FD18.10)';
COMMENT ON COLUMN unit_response.apparatus_resource_arrival_date_time IS 'CSV: Apparatus Resource Arrival Date Time (FD18.4)';
COMMENT ON COLUMN unit_response.apparatus_resource_arrival_at_hospital_date_time IS 'CSV: Apparatus Resource Arrival At Hospital Date Time (FD1.73)';
COMMENT ON COLUMN unit_response.apparatus_resource_clear_date_time IS 'CSV: Apparatus Resource Clear Date Time (FD18.5)';
COMMENT ON COLUMN unit_response.apparatus_resource_in_quarters_date_time IS 'CSV: Apparatus Resource In Quarters Date Time (FD1.74)';
COMMENT ON COLUMN unit_response.apparatus_resource_in_service_date_time IS 'CSV: Apparatus Resource In Service Date Time (FD18.5.1)';
COMMENT ON COLUMN unit_response.apparatus_resource_leave_scene_date_time IS 'CSV: Apparatus Resource Leave Scene Date Time (FD1.72)';

CREATE INDEX idx_unit_response_incident_id ON unit_response (incident_id);

-- ---------- ems_run ----------
CREATE TABLE ems_run (
  ems_run_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id integer NOT NULL REFERENCES incident(incident_id) ON DELETE CASCADE,
  response_incident_number varchar,
  response_ems_response_number varchar,
  response_ems_unit_call_sign varchar,
  response_ems_vehicle_unit_number varchar,
  response_level_of_care_of_this_unit varchar,
  incident_unit_left_scene_date_time timestamptz,
  incident_unit_left_scene_date_time_with_not_values varchar,
  incident_patient_arrived_at_destination_date_time timestamptz,
  incident_patient_arrived_at_destination_date_time_with_not_values varchar,
  incident_dispatch_priority_patient_acuity varchar,
  disposition_destination_name_delivered_transferred_to varchar,
  scene_gps_latitude numeric(9,6),
  scene_gps_longitude numeric(9,6),
  CONSTRAINT uq_ems_run_incident_response UNIQUE (
    response_incident_number,
    response_ems_response_number
  )
);

COMMENT ON TABLE ems_run IS 'EMS-specific unit response and times (many per incident).';
COMMENT ON COLUMN ems_run.incident_id IS 'FK to incident';
COMMENT ON COLUMN ems_run.response_incident_number IS 'CSV: Response Incident Number (eResponse.03)';
COMMENT ON COLUMN ems_run.response_ems_response_number IS 'CSV: Response EMS Response Number (eResponse.04)';
COMMENT ON COLUMN ems_run.response_ems_unit_call_sign IS 'CSV: Response EMS Unit Call Sign (eResponse.14)';
COMMENT ON COLUMN ems_run.response_ems_vehicle_unit_number IS 'CSV: Response EMS Vehicle Unit Number (eResponse.13)';
COMMENT ON COLUMN ems_run.response_level_of_care_of_this_unit IS 'CSV: Response Level Of Care Of This Unit (eResponse.15 / itResponse.115)';
COMMENT ON COLUMN ems_run.incident_unit_left_scene_date_time IS 'CSV: Incident Unit Left Scene Date Time (eTimes.09)';
COMMENT ON COLUMN ems_run.incident_unit_left_scene_date_time_with_not_values IS 'CSV: Incident Unit Left Scene Date Time With Not Values (eTimes.09)';
COMMENT ON COLUMN ems_run.incident_patient_arrived_at_destination_date_time IS 'CSV: Incident Patient Arrived At Destination Date Time (eTimes.11)';
COMMENT ON COLUMN ems_run.incident_patient_arrived_at_destination_date_time_with_not_values IS 'CSV: Incident Patient Arrived At Destination Date Time With Not Values (eTimes.11)';
COMMENT ON COLUMN ems_run.incident_dispatch_priority_patient_acuity IS 'CSV: Incident Dispatch Priority Patient Acuity (eDispatch.05)';
COMMENT ON COLUMN ems_run.disposition_destination_name_delivered_transferred_to IS 'CSV: Disposition Destination Name Delivered Transferred To (eDisposition.01)';
COMMENT ON COLUMN ems_run.scene_gps_latitude IS 'CSV: Scene GPS Latitude (eScene.11)';
COMMENT ON COLUMN ems_run.scene_gps_longitude IS 'CSV: Scene GPS Longitude (eScene.11)';

CREATE INDEX idx_ems_run_incident_id ON ems_run (incident_id);

CREATE TABLE IF NOT EXISTS fire_raw (
    id SERIAL PRIMARY KEY,
    "Basic Incident Number (FD1)" TEXT,
    "Basic Incident City Name (FD1.16)" TEXT,
    "Basic Primary Station Name (FD1.4)" TEXT,
    "Basic Incident Type Code (FD1.21)" TEXT,
    "Basic Incident Type Code And Description (FD1.21)" TEXT,
    "Basic Secondary Station Names List (FD1.4.1)" TEXT,
    "Basic Incident PSAP Date Time (FD1.51)" TEXT,
    "Basic Shift Or Platoon (FD1.30)" TEXT,
    "Apparatus Resource Dispatch Date Time (FD18.3)" TEXT,
    "Apparatus Resource En Route Date Time (FD18.10)" TEXT,
    "Apparatus Resource Arrival Date Time (FD18.4)" TEXT,
    "Apparatus Resource Arrival At Hospital Date Time (FD1.73)" TEXT,
    "Apparatus Resource Clear Date Time (FD18.5)" TEXT,
    "Apparatus Resource ID (FD18.1)" TEXT,
    "Basic Incident Year (FD1.3)" TEXT,
    "Basic Incident Month (FD1.3)" TEXT,
    "Basic Incident Day Of Month (FD1.3)" TEXT,
    "Basic Incident Day Of Week (FD1.3)" TEXT,
    "Basic Incident Week (FD1.3)" TEXT,
    "Basic Incident Day Name (FD1.3)" TEXT,
    "Basic Incident Type (FD1.21)" TEXT,
    "Apparatus Resource Type Category (FD18.2)" TEXT,
    "Apparatus Resource Type Code (FD18.2)" TEXT,
    "Basic Incident Postal Code (FD1.19)" TEXT,
    "Basic Arrival At Hospital Date Time (FD1.76)" TEXT,
    "Apparatus Resource In Quarters Date Time (FD1.74)" TEXT,
    "Apparatus Resource In Service Date Time (FD18.5.1)" TEXT,
    "Apparatus Resource Leave Scene Date Time (FD1.72)" TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ems_raw (
    id SERIAL PRIMARY KEY,
    "Response Incident Number (eResponse.03)" TEXT,
    "Response EMS Response Number (eResponse.04)" TEXT,
    "Response EMS Unit Call Sign (eResponse.14)" TEXT,
    "Response EMS Vehicle Unit Number (eResponse.13)" TEXT,
    "Response Level Of Care Of This Unit (3.4=eResponse.15/3.5=itResponse.115)" TEXT,
    "Incident Unit Left Scene Date Time (eTimes.09)" TEXT,
    "Incident Unit Left Scene Date Time With Not Values (eTimes.09)" TEXT,
    "Incident Patient Arrived At Destination Date Time (eTimes.11)" TEXT,
    "Incident Patient Arrived At Destination Date Time With Not Values (eTimes.11)" TEXT,
    "Incident Dispatch Priority Patient Acuity (eDispatch.05)" TEXT,
    "Disposition Destination Name Delivered Transferred To (eDisposition.01)" TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
